FROM ghcr.io/temirov/ghttp:latest

WORKDIR /srv/gravity

COPY index.html ./index.html
COPY styles.css ./styles.css
COPY sitemap.xml ./sitemap.xml
COPY CNAME ./CNAME
COPY privacy ./privacy
COPY js ./js

EXPOSE 8000

CMD ["--directory", "/srv/gravity", "8000"]
