name: Build and Publish Frontend Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile.frontend'
      - 'index.html'
      - 'js/**'
      - 'styles.css'
      - 'privacy/**'
      - 'sitemap.xml'
      - 'CNAME'
      - '.github/workflows/frontend-docker.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gravity-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
